#!/usr/bin/env python3
# Rebuilds freq.js: how common each of dict.js's common words is, so a game can
# tell an everyday word ("running") from a rarer one ("pinging"). Word hive
# uses it to judge how hard a day's letters are. See CLAUDE.md "the dictionary".
#
#   pip install --user wordfreq
#   python3 tools/build-freq.py        (run from anywhere; rerun after build-dict.py)
#
# freq.js holds one character per common word, in the same order as
# SortafunDict.common. Character code - 35 = zipf frequency x 10 - 29, so "#" is
# zipf 2.9 (the common cut-off) and each letter up is one tenth more common.
import os, wordfreq
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
raw = open('dict.js').read().split('window.SORTAFUN_DICT_RAW = "')[1].split('"')[0].split(' ')
common = [w.lower() for w in raw if w != w.lower()]
codes = ''.join(chr(35 + max(0, min(56, round(wordfreq.zipf_frequency(w, 'en') * 10) - 29))) for w in common)
assert '"' not in codes and '\\' not in codes
js = ('/* sortafun word frequencies. generated by tools/build-freq.py, do not hand edit.\n'
      '   SortafunFreq.zipf("word") -> 2.9 (just common) to ~7.7 ("the"), or 0 if the\n'
      '   word is not one of dict.js\'s common words. load after dict.js. */\n'
      'window.SORTAFUN_FREQ_RAW = "' + codes + '";\n'
      'window.SortafunFreq = (function () {\n'
      '  var map = null;\n'
      '  function build() {\n'
      '    if (map) return;\n'
      '    map = {};\n'
      '    var c = window.SortafunDict.common, r = window.SORTAFUN_FREQ_RAW;\n'
      '    if (c.length !== r.length) return; // dict.js changed without a rebuild: everything reads 0\n'
      '    for (var i = 0; i < c.length; i++) map[c[i]] = (r.charCodeAt(i) - 35 + 29) / 10;\n'
      '  }\n'
      '  return { zipf: function (w) { build(); return map[String(w).toLowerCase()] || 0; } };\n'
      '})();\n')
open('freq.js', 'w').write(js)
print(len(common), 'words,', len(js), 'bytes')
